name: "Test"

on:
  push:
  pull_request:
  schedule:
  - cron: '0 0 * * *'  # every day at midnight, to test against nightlies

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kongVersion:
        - "2.7.x"
        - "2.8.x"
        - "nightly"

    steps:
    - uses: actions/checkout@v3

    - uses: Kong/kong-pongo-action@v1
      with:
        kong_version: ${{ matrix.kongVersion }}

    - run: pongo run
